project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "Deep Learning for Forest Inventories"
  description: "Workshop on deep learning applications for enhanced forest inventories"
  favicon: "images/TreeNetwork.png"
  site-url: https://Brent-Murray.github.io/DeepLearningEFI/
  repo-url: https://github.com/Brent-Murray/DeepLearningEFI
  repo-actions: [issue]
  navbar:
    logo: "img/logo.png"
    left:
      - text: Home
        href: index.qmd
      - text: 1-Intro
        href: 01_intro.qmd
      - text: 2-Data
        href: 02_data.qmd
      - text: 3-Train
        href: 03_train.qmd
      - text: 4-Validation
        href: 04_validation.qmd
      - text: 5-Examples
        href: 05_examples.qmd
numbering: true

crossref:
  fig-prefix: "Figure"
  
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    page-layout: full

execute:
  freeze: auto
  echo: false
  warning: false
  error: false
  cache: true
  fig-num: true