project:
  type: website
  output-dir: docs

website:
  title: "Deep Learning for Forest Inventories"
  description: "Workshop on deep learning applications for enhanced forest inventories"
  site-url: https://Brent-Murray.github.io/DeepLearningEFI/
  repo-url: https://github.com/Brent-Murray/DeepLearningEFI
  repo-actions: [issue]
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: 1-Intro
        href: 01_intro.qmd
      - text: 2-Data
        href: 02_data.qmd
      - text: 3-Train
        href: 03_train.qmd
      - text: 4-Validation
        href: 04_validation.qmd
      - text: 5-Examples
        href: 05_examples.qmd

format:
  html:
    theme: sandstone
    toc: true
    page-layout: full

execute:
  freeze: auto
  echo: false
  warning: false
  error: false
  cache: true